### ISSUE TITLE
Suggestion: have `/jenkins-is-the-way/` instead of `/user-story/` in the URLs

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/stories#11]
The current URLs of most of the pages doesn't mean anything special with `/user-story/`:
https://stories.jenkins.io/user-story/to-improve-railway-signaling-solutions

I'm suggesting to put in place a redirection (or maybe replace the `user-story` from the paths and slugs in the code) to get `/jenkins-is-the-way/` in them, so the title of the stories is reflected in the URL and means something when reading them:
https://stories.jenkins.io/jenkins-is-the-way/to-improve-railway-signaling-solutions

Chat exchange:

> hervelemeur
> WDYT about replacing /user-story/ in the urls by /jenkins-is-the-way/ with a redirection for example?
> https://stories.jenkins.io/user-story/to-improve-railway-signaling-solutions would become https://stories.jenkins.io/jenkins-is-the-way/to-improve-railway-signaling-solutions

> MarkEWaite (Mark Waite)
> I'm not sure what we gain by that redirection. An original URL looked like this:
> 
> https://jenkinsistheway.io/user-story/jenkins-is-the-way-to-facilitate-day-to-day-work/
> 
> The same page on [stories.jenkins.io](http://stories.jenkins.io/) looks like this:
> 
> https://stories.jenkins.io/user-story/to-facilitate-day-to-day-work/
> 
> If your intent is to match the original URL, then I think that we would want to redirect from
> 
> https://stories.jenkins.io/user-story/jenkins-is-the-way-to-facilitate-day-to-day-work/
> 
> to
> 
> https://stories.jenkins.io/user-story/to-facilitate-day-to-day-work/

> hervelemeur
> [most of the stories in the repo](https://github.com/jenkins-infra/stories/tree/main/src/user-story) start with "to-...". I thought it was interesting to get the "Jenkins Is The Way" of the title also reflected in the URLs.
> (as a bonus, AFAIK it could help a little on the SEO side by having the url closely matching the page title)

> MarkEWaite (Mark Waite)
> Wouldn't it be even better for SEO if the original URL were matched?
> 
> https://jenkinsistheway.io/user-story/jenkins-is-the-way-to-facilitate-day-to-day-work/ (original)
> https://jenkinsistheway.io/user-story/to-facilitate-day-to-day-work/ (current)

> hervelemeur
> idk, I don't think so but not sure at all. I also think/hope there will be more new stories than old ones at a certain point, and that the new domain will take over the old one in search results.

> halkeye
> I can add a redirect pretty easily

**Comment by nouralmulhem** [comment]
can i tackle this one ?

**Comment by krisstern** [comment]
I do not think we should pursue this issue further as per feedback on #55.
